# Generated by Django 3.0.4 on 2020-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
