# Generated by Django 3.0.4 on 2020-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200305_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='reason_to_isolation',
            field=models.TextField(default='', max_length=300),
        ),
    ]
